name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch (change as needed)
  pull_request:
    branches:
      - main  # Optionally trigger on pull requests to main

jobs:
  build:
    name: Build and Deploy Site
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.92.2'
        extended: true

    - name: Install Node.js dependencies
      run: |
        npm install

    - name: Build site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages

